import { z } from "zod";

export const userSchema = z.object({
  id: z.number(),
  name: z.string(),
  email: z.string().email(),
  image: z.string().nullable(),
  role: z.string(),
  nickname: z.string().nullable(),
  gender: z.string(),
  className: z.string(),
  qrCode: z.string(),
});

export type UserRow = z.infer<typeof userSchema>;

export const dummyData: UserRow[] = [
  {
    id: 1,
    name: "Ahmad Fauzi",
    email: "ahmad@sekolah.id",
    image: null,
    role: "admin",
    nickname: null,
    gender: "laki-laki",
    className: "-",
    qrCode: "STU-ADM-0001",
  },
  {
    id: 2,
    name: "Budi Santoso",
    email: "budi@sekolah.id",
    image: null,
    role: "teacher",
    nickname: "Pak Budi",
    gender: "laki-laki",
    className: "TK A",
    qrCode: "a1b2c3d4-e5f6",
  },
  {
    id: 3,
    name: "Siti Nurhaliza",
    email: "siti@sekolah.id",
    image: null,
    role: "teacher",
    nickname: "Bu Siti",
    gender: "perempuan",
    className: "TK B",
    qrCode: "b2c3d4e5-f6a7",
  },
  {
    id: 4,
    name: "Dewi Lestari",
    email: "dewi@sekolah.id",
    image: null,
    role: "teacher",
    nickname: "Bu Dewi",
    gender: "perempuan",
    className: "TK A",
    qrCode: "c3d4e5f6-a7b8",
  },
  {
    id: 5,
    name: "Rudi Hartono",
    email: "rudi@sekolah.id",
    image: null,
    role: "staff",
    nickname: "Rudi",
    gender: "laki-laki",
    className: "",
    qrCode: "d4e5f6a7-b8c9",
  },
  {
    id: 6,
    name: "Ani Rahmawati",
    email: "ani@sekolah.id",
    image: null,
    role: "staff",
    nickname: "Ani",
    gender: "perempuan",
    className: "-",
    qrCode: "e5f6a7b8-c9d0",
  },
  {
    id: 7,
    name: "Hendra Gunawan",
    email: "hendra@sekolah.id",
    image: null,
    role: "teacher",
    nickname: "Pak Hendra",
    gender: "laki-laki",
    className: "TK B",
    qrCode: "f6a7b8c9-d0e1",
  },
  {
    id: 8,
    name: "Fitriani",
    email: "fitri@sekolah.id",
    image: null,
    role: "teacher",
    nickname: "Bu Fitri",
    gender: "perempuan",
    className: "KB",
    qrCode: "a7b8c9d0-e1f2",
  },
  {
    id: 9,
    name: "Supriyadi",
    email: "supri@sekolah.id",
    image: null,
    role: "staff",
    nickname: "Supri",
    gender: "laki-laki",
    className: "-",
    qrCode: "b8c9d0e1-f2a3",
  },
  {
    id: 10,
    name: "Lina Marlina",
    email: "lina@sekolah.id",
    image: null,
    role: "teacher",
    nickname: "Bu Lina",
    gender: "perempuan",
    className: "TK A",
    qrCode: "c9d0e1f2-a3b4",
  },
  {
    id: 11,
    name: "Agus Wijaya",
    email: "agus@sekolah.id",
    image: null,
    role: "admin",
    nickname: null,
    gender: "laki-laki",
    className: "-",
    qrCode: "STU-ADM-0002",
  },
  {
    id: 12,
    name: "Ratna Dewi",
    email: "ratna@sekolah.id",
    image: null,
    role: "teacher",
    nickname: "Bu Ratna",
    gender: "perempuan",
    className: "KB",
    qrCode: "d0e1f2a3-b4c5",
  },
];
